auth-server: http://localhost:8150

server:
  port: 8884
  servlet:
    context-path: /orderSystem
spring:
  application:
    name: order
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/

security:
  oauth2:
    client:
      client-id: OrderManagement
      client-secret: order123
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key
