auth-server: http://localhost:8150

server:
  port: 8883
  servlet:
    context-path: /memberSystem
spring:
  application:
    name: member
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/

# oauth2.0 客户端服务 + 资源服务 配置
security:
  oauth2:
    client:
      client-id: UserManagement
      client-secret: user123
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key


