server:
  port: 8150

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/

spring:
  application:
    name: sso
  datasource:
    url: jdbc:mysql://localhost:3306/test01?useUnicode=true&charachterEncoding=utf-8&userSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    password:
    port: 6379

# 微信开放平台 重定向url (填写你申请的信息)
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://guli.shop/api/ucenter/wx/callback